# Generated by Django 3.2 on 2023-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Наименование категории', max_length=256, unique=True, verbose_name='Категория'),
        ),
    ]
